config/routes.rb
Rails.application.routes.draw do
  root to: 'home#top'


  resources :users


  resources :rooms  

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'home/room_post'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :user, class_name: "user", foreign_key: "user_id"
    belongs_to :room, class_name: "room", foreign_key: "room_id"
end

app/models/room.rb
class Room < ApplicationRecord
    has_one_attached :image
    has_many :reservations, class_name: "reservation", foreign_key: "reference_id", dependent: :destroy
    belongs_to :user, class_name: "user", foreign_key: "user_id"
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_one_attached :image
    has_many :rooms, class_name: "room", foreign_key: "reference_id", dependent: :destroy
    has_many :reservations, class_name: "reservation", foreign_key: "reference_id", dependent: :destroy

    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user

    private

    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def room_post
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find?by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_path notice: 'ログインしました。'
    else
    render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_path notice: 'ログアウトしました。'
  end
  
  
  private
  def session_params
    params.require(:session).permit(:email, :password)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save 
      redirect_to root_path, notice: "ユーザー「#{@user.name}」を新規登録しました。"
    else
      render :new
    end
  end
  

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def update
    @user = User.find(params[:id])
    
    if @user.update(user_params)
      redirect_to users_path, notice: "ユーザー情報を更新しました。"
    else
      render :edit
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path, notice: "ユーザーを削除しました。"
  end
  
  
  

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :description ,:image)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/room_post.html.erb
<h1>Home#room_post</h1>
<p>Find me in app/views/home/room_post.html.erb</p>

app/views/home/top.html.erb
<div class="top">
    <div class="top-main">
        <div class="container">
            <div class="row col-lg-6">
                <div class="form-fream">
                    <div class="form-area">
                        <p class="form-area-title mb-4">Potepan Shareでまだ体験したことのない旅をしよう</p>
                        <form action="https://presite-potepancamp-rails-02.herokuapp.com/rooms/search" accept-charset="UTF-8" method="get">
                            <label for="___">エリア</label>
                            <input type="text" name="area" id="area" value="" class="form-control mb-4" placeholder="東京">
                            <input type="submit" name="commit" value="探す" class="form-control btn-primary mb-4" data-disable-with="探す">
                        </form>                    
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="panel-area m-5">
            <h1 class="section-title">おすすめのエリア</h1>
            <div class="row">
                <div class="panel-item col-lg-3 col-6">
                    東京
                    <%= link_to image_tag("tokyo.png",class:"panel-image"), '/'%>
                    <div class="shadow"></div>
                </div>
                <div class="panel-item col-lg-3 col-6">
                    大阪
                    <%= link_to image_tag("osaka.webp",class:"panel-image"), '/'%>
                </div>
                <div class="panel-item col-lg-3 col-6">
                    京都
                    <%= link_to image_tag("kyoto.jpeg",class:"panel-image"), '/'%>
                    <div class="shadow"></div>
                </div>
                <div class="panel-item col-lg-3 col-6">
                    札幌
                    <%= link_to image_tag("sapporo.jpeg",class:"panel-image"), '/'%>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tra</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="header-inner">
        <div class="header-left-nav">
          <a href="/"><img alt="サイトのロゴ画像" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png"></a>
          <form action="https://presite-potepancamp-rails-02.herokuapp.com/rooms/search" accept-charset="UTF-8" method="get">
            <div class="header-sharch d-lg-inline-block d-none">
              <input type="text" name="area" id="area" value="" class="form-control" placeholder="エリア">
              <i class="fas fa-map-marker-alt"></i>
            </div>
            <div class="header-sharch d-lg-inline-block d-none">
              <input type="text" name="keyword" id="keyword" value="" class="form-control" placeholder="キーワード">
              <i class="fas fa-search"></i>
            </div>
            <input type="submit" name="commit" value="" class="d-none" data-disable-with="">
          </form>    
        </div>
        <div class="header-right-nav">
          <div class="nav-item d-sm-inline-block d-none">
            匠
          </div>
          <div class="nav-item">
            <img class="mx-3 p-1 host-icon nav-trigger" alt="メニュー" src="/uploads/user/image/1576/F2C4E3CC-3BF4-4646-B593-48172D4353C6.jpeg">
            <ul class="header-nav-menu">
              
              <% if current_user%>           
                <li><%= link_to "ルーム登録", new_room_path%></li>
                <li><%= link_to '予約済みルーム一覧', reservations_path %></li>
                <li><%= link_to '登録済みルーム一覧', rooms_path %></li>
                <li></li>
                <li><%= link_to destroy_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to 'ログイン', login_path%></li>
                <li><%= link_to '新規登録', new_user_path%></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </header>
    <div class="notifications">
    </div>
    
    <%= yield %>

    <div class="footerFixed">
      <footer class="footer">
      <p>© 2020 POTEPAN.INC.</p>
      </footer>
    </div>
  </body>
</html>

app/views/rooms/index.html.erb
<h1>Rooms#index</h1>
<p>Find me in app/views/rooms/index.html.erb</p>

app/views/rooms/new.html.erb
<h1>Rooms#new</h1>
<p>Find me in app/views/rooms/new.html.erb</p>

app/views/rooms/show.html.erb
<h1>Rooms#show</h1>
<p>Find me in app/views/rooms/show.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<table>
   <thead>
     <tr>
       <th>id</th>
       <th>名前</th>
       <th>メールアドレス</th>
       <th>年齢</th>
       <th>一言紹介</th>
       <th>更新日</th>
       <th>作成日</th>
       <th>参照</th>
       <th>編集</th>
       <th>削除</th>
     </tr>
   </thead>
 
   <tbody>
     <% @users.each do |user| %>
       <tr>
         <td><%= user.id %></td>
         <td><%= user.name %></td>
         <td><%= user.email %></td>
         <td><%= user.description %></td>
         <td><%= user.updated_at.to_s(:datetime_jp) %></td>
         <td><%= user.created_at.to_s(:datetime_jp) %></td>
         <td>
           <%= link_to "参照", user %>
         </td>
         <td>
           <%= link_to "編集", [:edit, user] %>
         </td>
         <td>
           <%= link_to "削除", user, method: :delete, data: { confirm: "本当に削除しますか？" } %>
         </td>
       </tr>
     <% end %>
   </tbody>
 </table>

app/views/users/new.html.erb
<%form_with%>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>